DROP DATABASE IF EXISTS supermarket;

CREATE DATABASE supermarket;

USE supermarket;

CREATE TABLE items (
    PID INT PRIMARY KEY,
    PNAME VARCHAR(50) NOT NULL,
    PTYPE VARCHAR(50) NOT NULL,
    PCOST FLOAT NOT NULL,
    PQTY INT
);

CREATE TABLE staff (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50) UNIQUE,
    DEPT VARCHAR(50) NOT NULL,
    PHONE INT,
    SALARY FLOAT,
    EMAIL CHAR(70),
    DOJ DATE
);

SHOW TABLES;

DESC items;

DESC staff;